// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod babylon {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_PRECISION: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_PRECISION: i8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_PRECISION: [Precision; 3] = [
  Precision::F32,
  Precision::F16,
  Precision::INT8,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Precision(pub i8);
#[allow(non_upper_case_globals)]
impl Precision {
  pub const F32: Self = Self(0);
  pub const F16: Self = Self(1);
  pub const INT8: Self = Self(2);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::F32,
    Self::F16,
    Self::INT8,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::F32 => Some("F32"),
      Self::F16 => Some("F16"),
      Self::INT8 => Some("INT8"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for Precision {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for Precision {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for Precision {
    type Output = Precision;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for Precision {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Precision {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Precision {}
pub enum SemanticPacketOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SemanticPacket<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SemanticPacket<'a> {
  type Inner = SemanticPacket<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SemanticPacket<'a> {
  pub const VT_SESSION_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_SEQUENCE_ID: ::flatbuffers::VOffsetT = 6;
  pub const VT_GHOST_HASH: ::flatbuffers::VOffsetT = 8;
  pub const VT_PRECISION: ::flatbuffers::VOffsetT = 10;
  pub const VT_EMBEDDING_DATA: ::flatbuffers::VOffsetT = 12;
  pub const VT_LANGUAGE_HINT: ::flatbuffers::VOffsetT = 14;
  pub const VT_TIMESTAMP: ::flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SemanticPacket { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SemanticPacketArgs<'args>
  ) -> ::flatbuffers::WIPOffset<SemanticPacket<'bldr>> {
    let mut builder = SemanticPacketBuilder::new(_fbb);
    builder.add_timestamp(args.timestamp);
    builder.add_ghost_hash(args.ghost_hash);
    builder.add_session_id(args.session_id);
    if let Some(x) = args.language_hint { builder.add_language_hint(x); }
    if let Some(x) = args.embedding_data { builder.add_embedding_data(x); }
    builder.add_sequence_id(args.sequence_id);
    builder.add_precision(args.precision);
    builder.finish()
  }


  #[inline]
  pub fn session_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(SemanticPacket::VT_SESSION_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn sequence_id(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(SemanticPacket::VT_SEQUENCE_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn ghost_hash(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(SemanticPacket::VT_GHOST_HASH, Some(0)).unwrap()}
  }
  #[inline]
  pub fn precision(&self) -> Precision {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Precision>(SemanticPacket::VT_PRECISION, Some(Precision::F32)).unwrap()}
  }
  #[inline]
  pub fn embedding_data(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(SemanticPacket::VT_EMBEDDING_DATA, None)}
  }
  #[inline]
  pub fn language_hint(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(SemanticPacket::VT_LANGUAGE_HINT, None)}
  }
  #[inline]
  pub fn timestamp(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(SemanticPacket::VT_TIMESTAMP, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for SemanticPacket<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("session_id", Self::VT_SESSION_ID, false)?
     .visit_field::<u32>("sequence_id", Self::VT_SEQUENCE_ID, false)?
     .visit_field::<u64>("ghost_hash", Self::VT_GHOST_HASH, false)?
     .visit_field::<Precision>("precision", Self::VT_PRECISION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("embedding_data", Self::VT_EMBEDDING_DATA, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("language_hint", Self::VT_LANGUAGE_HINT, false)?
     .visit_field::<u64>("timestamp", Self::VT_TIMESTAMP, false)?
     .finish();
    Ok(())
  }
}
pub struct SemanticPacketArgs<'a> {
    pub session_id: u64,
    pub sequence_id: u32,
    pub ghost_hash: u64,
    pub precision: Precision,
    pub embedding_data: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub language_hint: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub timestamp: u64,
}
impl<'a> Default for SemanticPacketArgs<'a> {
  #[inline]
  fn default() -> Self {
    SemanticPacketArgs {
      session_id: 0,
      sequence_id: 0,
      ghost_hash: 0,
      precision: Precision::F32,
      embedding_data: None,
      language_hint: None,
      timestamp: 0,
    }
  }
}

pub struct SemanticPacketBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SemanticPacketBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_session_id(&mut self, session_id: u64) {
    self.fbb_.push_slot::<u64>(SemanticPacket::VT_SESSION_ID, session_id, 0);
  }
  #[inline]
  pub fn add_sequence_id(&mut self, sequence_id: u32) {
    self.fbb_.push_slot::<u32>(SemanticPacket::VT_SEQUENCE_ID, sequence_id, 0);
  }
  #[inline]
  pub fn add_ghost_hash(&mut self, ghost_hash: u64) {
    self.fbb_.push_slot::<u64>(SemanticPacket::VT_GHOST_HASH, ghost_hash, 0);
  }
  #[inline]
  pub fn add_precision(&mut self, precision: Precision) {
    self.fbb_.push_slot::<Precision>(SemanticPacket::VT_PRECISION, precision, Precision::F32);
  }
  #[inline]
  pub fn add_embedding_data(&mut self, embedding_data: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SemanticPacket::VT_EMBEDDING_DATA, embedding_data);
  }
  #[inline]
  pub fn add_language_hint(&mut self, language_hint: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SemanticPacket::VT_LANGUAGE_HINT, language_hint);
  }
  #[inline]
  pub fn add_timestamp(&mut self, timestamp: u64) {
    self.fbb_.push_slot::<u64>(SemanticPacket::VT_TIMESTAMP, timestamp, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SemanticPacketBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SemanticPacketBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SemanticPacket<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SemanticPacket<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SemanticPacket");
      ds.field("session_id", &self.session_id());
      ds.field("sequence_id", &self.sequence_id());
      ds.field("ghost_hash", &self.ghost_hash());
      ds.field("precision", &self.precision());
      ds.field("embedding_data", &self.embedding_data());
      ds.field("language_hint", &self.language_hint());
      ds.field("timestamp", &self.timestamp());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `SemanticPacket`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_semantic_packet_unchecked`.
pub fn root_as_semantic_packet(buf: &[u8]) -> Result<SemanticPacket<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<SemanticPacket>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `SemanticPacket` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_semantic_packet_unchecked`.
pub fn size_prefixed_root_as_semantic_packet(buf: &[u8]) -> Result<SemanticPacket<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<SemanticPacket>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `SemanticPacket` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_semantic_packet_unchecked`.
pub fn root_as_semantic_packet_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<SemanticPacket<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<SemanticPacket<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `SemanticPacket` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_semantic_packet_unchecked`.
pub fn size_prefixed_root_as_semantic_packet_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<SemanticPacket<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<SemanticPacket<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a SemanticPacket and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `SemanticPacket`.
pub unsafe fn root_as_semantic_packet_unchecked(buf: &[u8]) -> SemanticPacket<'_> {
  unsafe { ::flatbuffers::root_unchecked::<SemanticPacket>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed SemanticPacket and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `SemanticPacket`.
pub unsafe fn size_prefixed_root_as_semantic_packet_unchecked(buf: &[u8]) -> SemanticPacket<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<SemanticPacket>(buf) }
}
#[inline]
pub fn finish_semantic_packet_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<SemanticPacket<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_semantic_packet_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<SemanticPacket<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod Babylon

